services:
  - type: web
    name: voyage-travel-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: CONTACT_EMAIL_TO
        sync: false
      - key: CONTACT_EMAIL_FROM
        sync: false
